services:
  ms-user-resources:
    build:
      context: ./ms-user-resources
      dockerfile: Dockerfile
    volumes:
      - /tmp
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DATABASE=${MONGO_DATABASE}
    env_file:
      - ./.env
    ports:
      - "8083:8083"
    networks:
      - ms-user-resources-network

networks:
  ms-user-resources-network:
    driver: bridge
